---
- hosts: all
  tasks:
  - name: Install the latest version of Python3
    yum:
      name: python3
      state: latest
  - name: Install pycrytodome python package
    pip:
      name: pycrytodome