---
- hosts: all
  tasks:
  - name: Install the latest version of Python3
    yum:
      name: python3
      state: latest
  - name: Install pycryptodome python package
    pip:
      name: pycryptodome
  - name: Install flask_sqlalchemy python package
    pip:
      name: flask_sqlalchemy
  - name: Install waitress python package
    pip:
      name: waitress
  - name: Clone a github repository
    git:
      repo: https://gitlab.com/kayjeng4/beetest1.git
      dest: /root/webapp/
      clone: yes
      update: yes
  - name: execute python script for testing webhook
    command: python3 /root/webapp/webapp.py